const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('studio', {
  loadState: () => ipcRenderer.invoke('state:load'),
  saveProfile: (profile) => ipcRenderer.invoke('state:save-profile', profile),
  saveExecution: (execution) => ipcRenderer.invoke('state:save-execution', execution),
  saveProvider: (provider) => ipcRenderer.invoke('provider:save', provider),
  saveYouTubeSecrets: (secrets) => ipcRenderer.invoke('youtube:save-secrets', secrets),
  connectYouTube: () => ipcRenderer.invoke('youtube:connect'),
  disconnectYouTube: () => ipcRenderer.invoke('youtube:disconnect'),
  saveMetaSecrets: (secrets) => ipcRenderer.invoke('meta:save-secrets', secrets),
  connectMeta: () => ipcRenderer.invoke('meta:connect'),
  disconnectMeta: () => ipcRenderer.invoke('meta:disconnect'),
  fetchYouTubeContext: (input) => ipcRenderer.invoke('youtube:fetch-context', input),
  fetchMetaContext: (input) => ipcRenderer.invoke('meta:fetch-context', input),
  chooseMedia: () => ipcRenderer.invoke('media:choose'),
  inspectMedia: (input) => ipcRenderer.invoke('media:inspect', input),
  runAnalysis: (context) => ipcRenderer.invoke('analysis:run', context),
  chat: (input) => ipcRenderer.invoke('llm:chat', input),
  simulate: (input) => ipcRenderer.invoke('execution:simulate', input),
  executeYouTube: (input) => ipcRenderer.invoke('execution:youtube', input),
  executeMeta: (input) => ipcRenderer.invoke('execution:meta', input),
  runYouTubeCycle: (input) => ipcRenderer.invoke('execution:youtube-cycle', input),
  runMetaCycle: (input) => ipcRenderer.invoke('execution:meta-cycle', input),
  listLedger: () => ipcRenderer.invoke('ledger:list'),
  listAccounts: () => ipcRenderer.invoke('accounts:list'),
  listReconciliation: () => ipcRenderer.invoke('reconciliation:list'),
  verifyReconciliation: (input) => ipcRenderer.invoke('reconciliation:verify', input),
  storageStatus: () => ipcRenderer.invoke('storage:status'),
  listMetrics: (input) => ipcRenderer.invoke('metrics:list', input),
  listExemplars: (input) => ipcRenderer.invoke('exemplars:list', input),
  pinExemplar: (input) => ipcRenderer.invoke('exemplars:pin', input),
  listEvaluationExamples: (input) => ipcRenderer.invoke('evaluation-examples:list', input),
  listCapabilities: () => ipcRenderer.invoke('capabilities:list'),
});
